---
title: 'The Analytics Say "Go For It"'
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
library(nflfastR)
library(tidyverse)
library(htmltools)
library(reactable)
library(sparkline)
```

```{r data}
# seasons <- 2010:2020
# fourth_down_plays <- purrr::map_df(seasons, function(x) {
#   readRDS(
#     url(
#       glue::glue("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_{x}.rds")
#     )
#   )
# }) %>%
#   filter(
#     down == 4,
#     qb_kneel == 0,
#     # rush == 1 | pass == 1,
#     !is.na(posteam),
#     !is.na(yardline_100),
#     !is.na(score_differential)
#   )

### to get latest data, run the script above. to get data through week 7 of the 2020 NFL season read in the csv below 
fourth_down_plays <- read.csv("fourth_down_plays_since_2010.csv")

go_for_it <- fourth_down_plays %>%
  mutate(
    yards_to_go = case_when(
      ydstogo <= 2 ~ "2 or less",
      ydstogo >= 3 & ydstogo <= 5 ~ "3 to 5",
      ydstogo >= 6 ~ "6 or more",
      TRUE ~ "NA"
    )
  ) %>%
  mutate(
    play_type = case_when(
      play_type == "field_goal" | play_type == "punt" ~ "Punt/FG",
      play_type == "run" | play_type == "pass" ~ "Run/Pass",
      play_type == "no_play" ~ "Penalty",
      TRUE ~ "NA"
    )
  ) %>%
  filter(yards_to_go == "2 or less",
         play_type != "Penalty") %>%
  dplyr::group_by(season, posteam, play_type) %>%
  summarize(n = n()) %>%
  mutate(`2010-2020` = round(100 * (n / sum(n)), 1)) %>%
  filter(play_type == "Run/Pass") %>%
  ungroup() %>%
  arrange(posteam, season) %>%
  left_join(teams_colors_logos, by = c('posteam' = 'team_abbr'))

trend <- go_for_it %>%
  ungroup() %>%
  select(team = posteam, `2010-2020`) %>%
  group_by(team) %>%
  mutate(`2010-2020` = list(`2010-2020`)) %>%
  distinct(team, `2010-2020`) %>%
  ungroup()

go_for_it_by_year <- go_for_it %>%
  select(season, team = posteam, `2010-2020`) %>%
  pivot_wider(names_from = "season", values_from = "2010-2020") %>%
  ungroup() %>%
  inner_join(trend, by = c("team" = "team")) 
```


```{r table}
make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x)
    rgb(get_color(x), maxColorValue = 255)
}

orange_pal <-
  make_color_pal(c(
    "#fef4eb",
    "#facba6",
    "#f8b58b",
    "#f59e72",
    "#f2855d",
    "#ef6a4c"
  ),
  bias = 0.7)

pct_col <- colDef(
  maxWidth = 60,
  class = "number",
  footer = function(value)
    paste0(sprintf("%.1f", mean(value)),"%"),
  cell = function(value)
    paste0(format(
      value, digits = 1, nsmall = 1
    ), "%"),
  style = function(y) {
    normalized <-
      (y - min(go_for_it$`2010-2020`, na.rm = TRUE)) / (max(go_for_it$`2010-2020`, na.rm =
                                                              TRUE) - min(go_for_it$`2010-2020`, na.rm = TRUE))
    color <- orange_pal(normalized)
    list(background = color)
  }
)

table <- reactable(
  go_for_it_by_year,
  pagination = FALSE,
  showSortIcon = FALSE,
  compact = TRUE,
  defaultSorted = "2020",
  defaultSortOrder = "desc",
  columns = list(
    team = colDef(
      maxWidth = 60,
      align = "center",
      footer = "Avg",
      cell = function(value, index) {
        ### Team logos from images folder
        img_src <-
          knitr::image_uri(sprintf("NFL_LOGOS/%s.png", value))
        image <- img(class = "logo",
                     src = img_src,
                     alt = value)
        div(class = "team", image)
      }
    ),
    `2010` = pct_col,
    `2011` = pct_col,
    `2012` = pct_col,
    `2013` = pct_col,
    `2014` = pct_col,
    `2015` = pct_col,
    `2016` = pct_col,
    `2017` = pct_col,
    `2018` = pct_col,
    `2019` = pct_col,
    `2020` = pct_col,
    `2010-2020` = colDef(
      maxWidth = 100,
      align = "right",
      class = "border-left",
      cell = function(value, index) {
        sparkline(
          go_for_it_by_year$`2010-2020`[[index]],
          type = "line",
          width = 90,
          height = 30,
          lineColor = "black",
          lineWidth = 2,
          fillColor = FALSE,
          spotRadius = 2,
          spotColor = NULL,
          minSpotColor = NULL,
          maxSpotColor = NULL
        )
      }
    )
  ),
  defaultColDef = colDef(
    headerClass = "header colheader",
    footerStyle = list(fontWeight = "bold", fontSize = "14px")
  )
)

### Add title and subtitle to top of page above table
div(
  class = "analytics",
  div(class = "title",
      "The rate at which NFL teams go for it on 4th & 2-or-less is at an all-time high largely due to the increased use of analytics in decision making."),
  table,
  ### Add  source below the table
  tags$span(style = "color:#999",
            div(
              "Note: Percentages shown are how often a team went for it (did not kick a field goal or punt the ball) when it was 4th & 2-or-less). Plays that were nullified due to penalties are not included."
            ),
            div(
              "TABLE: KYLE CUILLA @KC_ANALYTICS  •  DATA: NFLFASTR"
            ))
)
```

```{r}
### Load font from Google Fonts
tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```

```{css}
/* column border */
.border-left {
  border-left: 2px solid #666;
}

/* Column hover formatting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #dadada;
}

.header:active,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #333;
  color: #fff;
}


/* Column header formatting */
.colheader {
  font-family: "Open Sans", sans-serif;
  font-size: 12px;
  border-bottom: 2px solid #555;
  text-transform: uppercase;
}


/* Number formatting */
.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 13px;
  line-height: 34px;
  white-space: pre;
}


/* Text formatting */
.analytics {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
}

.logo {
  margin-right: 1px;
  height: 36px;
}


/* Formatting for title above table */
.title {
  font-family: "Open Sans", sans-serif;
  font-size: 16px;
  margin: 16px 0;
}
```


